/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRouteImport } from './routes/api'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IpPolicyRouteImport } from './routes/ip-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as TermsRouteImport } from './routes/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoute = ApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IpPolicyRoute = IpPolicyRouteImport.update({
  id: '/ip-policy',
  path: '/ip-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/history': typeof HistoryRoute
  '/ip-policy': typeof IpPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/history': typeof HistoryRoute
  '/ip-policy': typeof IpPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api': typeof ApiRoute
  '/history': typeof HistoryRoute
  '/ip-policy': typeof IpPolicyRoute
  '/privacy': typeof PrivacyRoute
  '/scan': typeof ScanRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api' | '/history' | '/ip-policy' | '/privacy' | '/scan' | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api' | '/history' | '/ip-policy' | '/privacy' | '/scan' | '/terms'
  id:
    | '__root__'
    | '/'
    | '/api'
    | '/history'
    | '/ip-policy'
    | '/privacy'
    | '/scan'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoute: typeof ApiRoute
  HistoryRoute: typeof HistoryRoute
  IpPolicyRoute: typeof IpPolicyRoute
  PrivacyRoute: typeof PrivacyRoute
  ScanRoute: typeof ScanRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api': {
      id: '/api'
      path: '/api'
      fullPath: '/api'
      preLoaderRoute: typeof ApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-policy': {
      id: '/ip-policy'
      path: '/ip-policy'
      fullPath: '/ip-policy'
      preLoaderRoute: typeof IpPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoute: ApiRoute,
  HistoryRoute: HistoryRoute,
  IpPolicyRoute: IpPolicyRoute,
  PrivacyRoute: PrivacyRoute,
  ScanRoute: ScanRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
